### ISSUE TITLE
Not working on Elementary OS

### ISSUE THREAD

**Issue by jacklenox** [kylerankin/psmouse-byd-dkms#8]
Hi there, I'm trying to get this to work on Elementary OS so that I can use my trackpad. I'm getting this error:

```
ERROR (dkms apport): binary package for psmouse: byd-0.2 not found
Error! Bad return status for module build on kernel: 3.19.0-39-generic (x86_64)
```

Any ideas?

**Comment by kylerankin** [comment]
I've only tested it on Debian stretch and Fedora and in the case of Fedora it requires you to build a custom kernel that makes psmouse a module (otherwise psmouse is built into the kernel). It's possible Elementary OS has a similar kernel that builds psmouse in. Also this module code is from the 4.x kernel series. 3.19 may be recent enough that it doesn't matter but I'm not sure.

**Comment by jacklenox** [comment]
Thanks for the response. You're right about the kernel, I tried updating to 4.x and it now works (thanks to some help and advice on the Purism forums). I've noticed that for me I can install the driver on 4.0 and 4.1, but anything above that and it doesn't work with a similar error. Unfortunately this means I don't get two finger scrolling. The option for two finger scrolling appears when the kernel is either at 4.2 or higher, but the touchpad stops working with the cursor just hopping about in the very top right of the screen. As above, I can't install the drivers on 4.2 and above. So it's a bit of a catch 22 if I want two finger scrolling!

Anyway, thanks for this Kyle, upgrading my kernel and installing this driver has made the laptop much more usable (I hate touch to click as my hands often wander over the pad while typing and previously wasn't able to switch it off!)
